# Generated by Django 3.2.3 on 2021-05-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        ('apostillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostilla',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Tramite'),
        ),
    ]
