# Generated by Django 3.2.3 on 2021-06-07 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del club')),
                ('nombre_presidente', models.CharField(max_length=60, verbose_name='Nombre del presidente(a)')),
                ('correo_presidente', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección del club')),
                ('num_telefonico', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre(s)')),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='curp',
            field=models.CharField(default='', max_length=18, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del grupo')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.club', verbose_name='Club')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.representante', verbose_name='Representante')),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='grupo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.grupo', verbose_name='Grupo'),
        ),
    ]
