# Generated by Django 3.2.3 on 2021-06-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_auto_20210607_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='curp',
        ),
    ]
