# Generated by Django 3.2.3 on 2021-06-04 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitoLocalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(max_length=10, verbose_name='Ámbito de localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.CharField(max_length=60, verbose_name='Tipo de discapacidad')),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=20, verbose_name='Estado Civil')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoVulnerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_vulnerable', models.CharField(max_length=80, verbose_name='Grupo vulnerable')),
            ],
            options={
                'verbose_name': 'Grupo vulnerable',
                'verbose_name_plural': 'Grupos vulnerables',
            },
        ),
        migrations.CreateModel(
            name='IdentificacionOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30, verbose_name='Tipo de identificación')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripción del ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='NivelEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_estudio', models.CharField(max_length=20, verbose_name='Nivel de estudios')),
            ],
            options={
                'verbose_name': 'Nivel de estudio',
                'verbose_name_plural': 'Niveles de estudio',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=30, verbose_name='Tipo de ocupación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguridad_social', models.CharField(max_length=20, verbose_name='Seguridad social')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vialidad', models.CharField(max_length=20, verbose_name='Tipo de vialidad')),
            ],
            options={
                'verbose_name': 'Tipo de vialidad',
                'verbose_name_plural': 'Tipos de vialidades',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivienda', models.CharField(max_length=20, verbose_name='Tipo de vivienda')),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Localidad')),
                ('ambito', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.ambitolocalidad', verbose_name='Ámbito')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Asentamiento',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[1-9]\\d*$')], verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Asentamiento')),
                ('tipo_asentamiento', models.PositiveIntegerField(verbose_name='Tipo de asentamiento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Asentamiento',
                'verbose_name_plural': 'Asentamientos',
            },
        ),
    ]
