# Generated by Django 3.2.3 on 2021-05-26 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitoLocalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(max_length=10, verbose_name='Ámbito de localidad')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='ambito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.ambitolocalidad', verbose_name='Ámbito'),
        ),
    ]
