# Generated by Django 3.2.3 on 2021-05-26 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20210526_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asentamiento',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='ID'),
        ),
    ]
