# Generated by Django 3.2.3 on 2021-05-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_asentamiento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asentamiento',
            name='tipo_asentamiento',
            field=models.PositiveIntegerField(verbose_name='Tipo de asentamiento'),
        ),
    ]
