# Generated by Django 3.2.3 on 2021-06-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasaporte', models.BooleanField(default=False, verbose_name='Pasaporte')),
                ('direccion_usa', models.CharField(max_length=70, verbose_name='Dirección de Estados Unidos')),
                ('persona_visitar', models.CharField(max_length=70, verbose_name='Nombre de la persona a visitar')),
                ('tel_persona_visitar', models.CharField(max_length=10, verbose_name='Teléfono de la persona a visitar')),
                ('fe_nacimiento_madre', models.DateField(verbose_name='Fecha de nacimiento de la madre')),
                ('fe_nacimiento_padre', models.DateField(verbose_name='Fecha de nacimiento del padre')),
                ('dir_trabajo_escuela', models.CharField(max_length=80, verbose_name='Dirección del lugar de trabajo o escuela')),
                ('nom_dir_trabajo_escuela', models.CharField(max_length=35, verbose_name='Nombre de la dirección del trabajo o escuela')),
                ('fe_ingreso_trabajo_escuela', models.DateField(verbose_name='Fecha de ingreso al trabajo o escuela')),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingreso Mensual')),
                ('fecha_viaje', models.DateField(verbose_name='Fecha tentativa de viaje')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('pago', models.BooleanField(default=False)),
                ('fecha_cita', models.DateField(blank=True, null=True, verbose_name='Fecha de la cita en el consulado')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
        migrations.CreateModel(
            name='VisaRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_social', models.URLField(verbose_name='URL de la red social')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visas.visa', verbose_name='Trámite de visa')),
            ],
        ),
    ]
