# Generated by Django 3.2.3 on 2021-06-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0002_alter_visa_asesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la cita en el consulado'),
        ),
    ]
