# Generated by Django 3.2.3 on 2021-06-04 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localizacion_personas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
            },
        ),
        migrations.CreateModel(
            name='PersonaDesaparecida',
            fields=[
                ('folio', models.IntegerField(default=localizacion_personas.models.autoincremento_folio, primary_key=True, serialize=False, verbose_name='folio')),
                ('nombre_desaparecido', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno_desaparecido', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno_desaparecido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('fecha_nacimiento_desaparecido', models.DateField(verbose_name='Fecha de nacimiento')),
                ('observaciones', models.CharField(max_length=150, verbose_name='Observaciones')),
                ('ultimo_lugar', models.CharField(max_length=30, verbose_name='Última lugar dónde se sabe al desaparecido(a)')),
                ('fecha_desaparicion', models.DateField(verbose_name='Fecha de desaparición')),
                ('telefono_solicitante', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\d{10})$')], verbose_name='Teléfono')),
                ('nombre_solicitante', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno_solicitante', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno_solicitante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion_personas.estatus', verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Persona desaparecida',
                'verbose_name_plural': 'Personas desaparecidas',
            },
        ),
    ]
