# Generated by Django 3.2.3 on 2021-05-27 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaDesaparecida',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('/^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$/')], verbose_name='CURP de la persona desaparecida')),
                ('nombre_desaparecido', models.CharField(max_length=50, verbose_name='Nombre de la persona desaparecida')),
                ('apellido_paterno_desaparecido', models.CharField(max_length=50, verbose_name='Apellido paterno de la persona desaparecida')),
                ('apellido_materno_desaparecido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno de la persona desaparecida')),
                ('fecha_nacimiento_desaparecido', models.DateField(verbose_name='Fecha de nacimiento de la persona desaparecida')),
                ('observaciones', models.CharField(max_length=150, verbose_name='Observaciones')),
                ('estatus', models.CharField(max_length=30, verbose_name='Estatus')),
                ('ultimo_lugar', models.CharField(max_length=30, verbose_name='Último lugar donde fue visto')),
                ('fecha_desaparicion', models.DateField(verbose_name='Fecha de desaparición')),
                ('telefono_solicitante', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]\\d*$')], verbose_name='Teléfono del solicitante')),
                ('nombre_solicitante', models.CharField(max_length=50, verbose_name='Nombre del solicitante')),
                ('apellido_paterno_solicitante', models.CharField(max_length=50, verbose_name='Apellido paterno del solicitante')),
                ('apellido_materno_solicitante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno del solicitante')),
            ],
        ),
    ]
