# Generated by Django 3.2.3 on 2021-05-28 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion_personas', '0002_alter_personadesaparecida_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
            },
        ),
        migrations.AlterModelOptions(
            name='personadesaparecida',
            options={'verbose_name': 'Persona desaparecida', 'verbose_name_plural': 'Personas desaparecidas'},
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='apellido_materno_desaparecido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='apellido_materno_solicitante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='apellido_paterno_desaparecido',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='apellido_paterno_solicitante',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='curp',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='fecha_nacimiento_desaparecido',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='nombre_desaparecido',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='nombre_solicitante',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='telefono_solicitante',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]\\d*$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='ultimo_lugar',
            field=models.CharField(max_length=30, verbose_name='Última lugar dónde se sabe al desaparecido(a)'),
        ),
        migrations.AlterField(
            model_name='personadesaparecida',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion_personas.estatus', verbose_name='Estatus'),
        ),
    ]
