# Generated by Django 3.2.3 on 2021-05-30 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion_personas', '0003_auto_20210528_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadesaparecida',
            name='telefono_solicitante',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\d{10})$')], verbose_name='Teléfono'),
        ),
    ]
