# Generated by Django 3.2.3 on 2021-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='alias',
            field=models.CharField(default=' ', max_length=30, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_apellido',
            field=models.CharField(default=' ', max_length=40, verbose_name='Apellido materno'),
        ),
    ]
