# Generated by Django 3.2.3 on 2021-06-07 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0003_remove_tramite_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionMigrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(default='', max_length=18, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP')),
                ('identificacion_oficial', models.BooleanField(verbose_name='Identificación Oficial')),
                ('curp_doc', models.BooleanField(verbose_name='CURP')),
                ('rfc', models.BooleanField(verbose_name='RFC')),
                ('solicitud_gobernador', models.BooleanField(verbose_name='Solicitud al gobernador')),
                ('hoja_deportacion', models.BooleanField(verbose_name='Hoja de deportación')),
                ('comprobante_domicilio', models.BooleanField(verbose_name='Comprobante de domicilio')),
                ('acta_nacimiento', models.BooleanField(verbose_name='Comprobante de domicilio')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
    ]
