# Generated by Django 3.2.3 on 2021-06-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_migrantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='acta_nacimiento',
            field=models.BooleanField(default=False, verbose_name='Comprobante de domicilio'),
        ),
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='comprobante_domicilio',
            field=models.BooleanField(default=False, verbose_name='Comprobante de domicilio'),
        ),
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='curp_doc',
            field=models.BooleanField(default=False, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='hoja_deportacion',
            field=models.BooleanField(default=False, verbose_name='Hoja de deportación'),
        ),
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='identificacion_oficial',
            field=models.BooleanField(default=False, verbose_name='Identificación Oficial'),
        ),
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='rfc',
            field=models.BooleanField(default=False, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='solicitud_gobernador',
            field=models.BooleanField(default=False, verbose_name='Solicitud al gobernador'),
        ),
    ]
