# Generated by Django 3.2.3 on 2021-06-04 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandamientosJudiciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_nac_original', models.BooleanField(default=False, verbose_name='Acta de Nacimiento Original')),
                ('curp_act', models.BooleanField(default=False, verbose_name='CURP Actualizada')),
                ('comprobante_domicilio', models.BooleanField(default=False, verbose_name='Comprobante domicilio')),
                ('pasaporte_vigente', models.BooleanField(default=False, verbose_name='Pasaporte vigente')),
                ('matricula_consular', models.BooleanField(default=False, verbose_name='Matrícula Consular')),
                ('pago_en_caja_fiscalia', models.BooleanField(default=False, verbose_name='Pago que se realiza en caja de fiscalia')),
                ('fotografia', models.BooleanField(default=False, verbose_name='1 Fotografía tamaño infantil blanco y negro con fondo blanco')),
                ('ine_familiar', models.BooleanField(default=False, verbose_name='INE del familiar directo que va a tramitar el documento')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaConducir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_nacimiento', models.BooleanField(default=False, verbose_name='Acta de Nacimiento')),
                ('comprobante_dom_eeuu', models.BooleanField(default=False, verbose_name='Comprobante de domicilio en Estados Unidos')),
                ('referencia_dom_zac', models.BooleanField(default=False, verbose_name='Domicilio de referencia en el Estado de Zacatecas')),
                ('fotografia', models.BooleanField(default=False, verbose_name='Fotografía')),
                ('tipo_sangre', models.CharField(max_length=3, verbose_name='Tipo de Sangre')),
                ('identificacion_oficial', models.BooleanField(default=False, verbose_name='Identificación oficial')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedicionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=100, verbose_name='Nombre del solicitante')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('municipio_registro', models.CharField(max_length=30, verbose_name='Municipio de registro')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
        migrations.CreateModel(
            name='DobleNacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_nacimiento_original', models.BooleanField(default=False, verbose_name='Acta de Nacimiento Original')),
                ('actas_apostilladas', models.BooleanField(default=False, verbose_name='Actas apostilladas')),
                ('comprobante_domicilio', models.BooleanField(default=False, verbose_name='Comprobante de domicilio')),
                ('identificacion_oficial', models.BooleanField(default=False, verbose_name='Identificación Oficial Padres')),
                ('original_copias', models.BooleanField(default=False, verbose_name='Original y 2 Copias')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
        migrations.CreateModel(
            name='DefensoriaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_realizar', models.CharField(max_length=80, verbose_name='Trámite a Realizar')),
                ('fecha', models.DateField(verbose_name='Fecha de trámite')),
                ('num_telefonico', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.localidad', verbose_name='Localidad')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
        migrations.CreateModel(
            name='CorreccionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_a_corregir', models.BooleanField(default=False, verbose_name='Acta a corregir')),
                ('documentos_comprobantes', models.BooleanField(default=False, verbose_name='Documentos que comprueben lo solicitado')),
                ('testimonial', models.BooleanField(default=False, verbose_name='Testimonial de 2 personas')),
                ('solicitud_firmado', models.BooleanField(default=False, verbose_name='Solicitud firmada')),
                ('original_copias', models.BooleanField(default=False, verbose_name='Original y 2 Copias')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(max_length=70, verbose_name='Nombre completo de la escuela')),
                ('anio_aprox', models.IntegerField(verbose_name='Año aproximado que se cursó el grado')),
                ('fotografia', models.BooleanField(default=False, verbose_name='Fografía, reciente, de frente, sin lentes, sin gorra o sombrero')),
                ('num_telefonico', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.localidad', verbose_name='Localidad')),
                ('nivel_estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.nivelestudios', verbose_name='Nivel de estudios')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
    ]
