# Generated by Django 3.2.3 on 2021-05-30 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apelldio Materno')),
                ('acta_a_corregir', models.BooleanField(default=False, verbose_name='Acta a corregir')),
                ('documentos_comprobantes', models.BooleanField(default=False, verbose_name='Documentos que comprueben lo solicitado')),
                ('testimonial', models.BooleanField(default=False, verbose_name='Testimonial de 2 personas')),
                ('solicitud_firmado', models.BooleanField(default=False, verbose_name='Solicitud firmada')),
                ('originasl_copias', models.BooleanField(default=False, verbose_name='Original y 2 Copias')),
            ],
        ),
        migrations.CreateModel(
            name='DobleNacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apelldio Materno')),
                ('acta_nacimiento_original', models.BooleanField(default=False, verbose_name='Acta de Nacimiento Original')),
                ('actas_apostilladas', models.BooleanField(default=False, verbose_name='Actas apostilladas')),
                ('comprobante_domicilio', models.BooleanField(default=False, verbose_name='Identificación Oficial Padres')),
                ('original_copias', models.BooleanField(default=False, verbose_name='Original y 2 Copias')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedicionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apelldio Materno')),
                ('nombre_solicitante', models.CharField(max_length=100, verbose_name='Nombre solicitante')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('municipio_registro', models.CharField(max_length=30, verbose_name='Municipio de registro')),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaCondunciar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apelldio Materno')),
                ('acta_nacimiento', models.BooleanField(default=False, verbose_name='Acta de Nacimiento')),
                ('comprobante_dom_eeuu', models.BooleanField(default=False, verbose_name='Comprobante de domicilio en Estados Unidos')),
                ('referencia_dom_zac', models.BooleanField(default=False, verbose_name='Domicilio de referencia en el Estado de Zacatecas')),
                ('fotografia', models.BooleanField(default=False, verbose_name='Fotografia')),
                ('tipo_sangre', models.CharField(max_length=3, verbose_name='Tipo de Sangre')),
                ('identificacion_oficial', models.BooleanField(default=False, verbose_name='Identificación oficial')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.estadotramite', verbose_name='Estatus de trámite')),
            ],
        ),
        migrations.CreateModel(
            name='DefensoriaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apelldio Materno')),
                ('tramite_realizar', models.CharField(max_length=80, verbose_name='Tramite a Realizar')),
                ('fecha', models.DateField(verbose_name='Fecha de trámite')),
                ('num_telefonico', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.localidad', verbose_name='Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaEstudios',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apelldio Materno')),
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP')),
                ('nombre_escuela', models.CharField(max_length=70, verbose_name='Nombre completo de la escuela')),
                ('anio_aprox', models.IntegerField(verbose_name='Localidad')),
                ('fotografia', models.BooleanField(default=False, verbose_name='Fotografia reciente')),
                ('num_telefonico', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.localidad', verbose_name='Localidad')),
                ('nivel_estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.nivelestudios', verbose_name='Nivel de estudios')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
    ]
