# Generated by Django 3.2.3 on 2021-05-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
        ('ferias_binacionales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenciaCondunciar',
            new_name='LicenciaConduncir',
        ),
    ]
