# Generated by Django 3.2.3 on 2021-06-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
        ('ferias_binacionales', '0002_rename_licenciacondunciar_licenciaconduncir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenciaConduncir',
            new_name='LicenciaConducir',
        ),
        migrations.RenameField(
            model_name='correccionacta',
            old_name='originasl_copias',
            new_name='original_copias',
        ),
    ]
