# Generated by Django 3.2.3 on 2021-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias_binacionales', '0003_auto_20210601_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandamientosJuciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apelldio Materno')),
                ('acta_nac_original', models.BooleanField(default=False, verbose_name='Acta de Nacimiento Original')),
                ('curp_act', models.BooleanField(default=False, verbose_name='CURP Actualizada')),
                ('comprobantE_domicilio', models.BooleanField(default=False, verbose_name='Comprobante domicilio')),
                ('pasaporte_vigente', models.BooleanField(default=False, verbose_name='Pasaporte vigente')),
                ('matricula_consular', models.BooleanField(default=False, verbose_name='Matrícula Consular')),
                ('pago_en_caja_fiscalia', models.BooleanField(default=False, verbose_name='Pago que se realiza en caja de fiscalia')),
                ('fotografia', models.BooleanField(default=False, verbose_name='1 Fotografía tamaño infantil blanco y negro con fonso blanco')),
                ('ine_familiar', models.BooleanField(default=False, verbose_name='INE del familiar directo que va a tramitar el documento')),
            ],
        ),
    ]
