# Generated by Django 3.2.3 on 2021-06-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferias_binacionales', '0004_mandamientosjuciales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MandamientosJuciales',
            new_name='MandamientosJudiciales',
        ),
    ]
