# Generated by Django 3.2.3 on 2021-06-01 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias_binacionales', '0005_rename_mandamientosjuciales_mandamientosjudiciales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constanciaestudios',
            name='tramite',
        ),
        migrations.AlterField(
            model_name='constanciaestudios',
            name='num_telefonico',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono'),
        ),
    ]
