# Generated by Django 3.2.3 on 2021-06-01 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias_binacionales', '0007_auto_20210601_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensoriapublica',
            name='num_telefonico',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='defensoriapublica',
            name='tramite_realizar',
            field=models.CharField(max_length=80, verbose_name='Trámite a Realizar'),
        ),
    ]
