# Generated by Django 3.2.3 on 2021-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias_binacionales', '0008_auto_20210601_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandamientosjudiciales',
            old_name='comprobantE_domicilio',
            new_name='comprobante_domicilio',
        ),
        migrations.AlterField(
            model_name='correccionacta',
            name='ap_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='correccionacta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='defensoriapublica',
            name='ap_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='defensoriapublica',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='doblenacionalidad',
            name='ap_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='doblenacionalidad',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='expedicionacta',
            name='ap_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='expedicionacta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='expedicionacta',
            name='nombre_solicitante',
            field=models.CharField(max_length=100, verbose_name='Nombre del solicitante'),
        ),
        migrations.AlterField(
            model_name='licenciaconducir',
            name='ap_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='licenciaconducir',
            name='fotografia',
            field=models.BooleanField(default=False, verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='licenciaconducir',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='mandamientosjudiciales',
            name='ap_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='mandamientosjudiciales',
            name='fotografia',
            field=models.BooleanField(default=False, verbose_name='1 Fotografía tamaño infantil blanco y negro con fondo blanco'),
        ),
        migrations.AlterField(
            model_name='mandamientosjudiciales',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
    ]
