# Generated by Django 3.2.3 on 2021-06-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias_binacionales', '0009_auto_20210601_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='doblenacionalidad',
            name='identificacion_oficial',
            field=models.BooleanField(default=False, verbose_name='Identificación Oficial Padres'),
        ),
        migrations.AlterField(
            model_name='doblenacionalidad',
            name='comprobante_domicilio',
            field=models.BooleanField(default=False, verbose_name='Comprobante de domicilio'),
        ),
    ]
