# Generated by Django 3.2.3 on 2021-06-04 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioSocioeconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio_socioeconomico', models.BooleanField(verbose_name='Presentó estudio socioeconómico')),
                ('jefe_familia', models.BooleanField(verbose_name='Es jefe de familia')),
                ('integrantes_familia', models.PositiveIntegerField(verbose_name='Número de integrantes de la familia')),
                ('dependientes_economicos', models.PositiveIntegerField(verbose_name='Número de dependeientes económicos')),
                ('numero_habitantes_vivienda', models.PositiveIntegerField(verbose_name='Número de habitantes en la vivienda')),
                ('vivienda_electricidad', models.BooleanField(default=False, verbose_name='Electricidad')),
                ('vivienda_agua', models.BooleanField(default=False, verbose_name='Agua corriente')),
                ('vivienda_drenaje', models.BooleanField(default=False, verbose_name='Drenaje')),
                ('vivienda_gas', models.BooleanField(default=False, verbose_name='Gas')),
                ('vivienda_telefono', models.BooleanField(default=False, verbose_name='Teléfono')),
                ('vivienda_internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.discapacidad', verbose_name='Discapacidad')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.estadocivil', verbose_name='Estado civíl')),
                ('grupo_vulnerable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.grupovulnerable', verbose_name='Grupo vulnerable')),
                ('ingreso_mensual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.ingresomensual', verbose_name='Ingreso mensual')),
                ('nivel_estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.nivelestudios', verbose_name='Nivel de estudios')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.ocupacion', verbose_name='Ocupación')),
                ('tipo_seguridad_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tiposeguridadsocial', verbose_name='Tipo de seguridad social')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.vivienda', verbose_name='Vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarioDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vialidad', models.CharField(max_length=50, verbose_name='Vialidad')),
                ('numero_exterior', models.PositiveIntegerField(verbose_name='Número exterior')),
                ('numero_interior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número interior')),
                ('entre_vialidades', models.CharField(blank=True, max_length=50, verbose_name='Entre vialidades')),
                ('descripcion_ubicacion', models.TextField(blank=True, verbose_name='Referencias de ubicación')),
                ('asentamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.asentamiento', verbose_name='Asentamiento')),
                ('tipo_vialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipovialidad', verbose_name='Tipo de vialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('beneficiario_colectivo', models.BooleanField(default=False, verbose_name='Es beneficiario colectivo')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiariodireccion', verbose_name='Dirección')),
                ('estudio_socioeconomico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.estudiosocioeconomico', verbose_name='Estudio Socioeconómico')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.identificacionoficial', verbose_name='Identificación Oficial')),
            ],
        ),
    ]
