# Generated by Django 3.2.3 on 2021-06-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiariodireccion', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estudio_socioeconomico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.estudiosocioeconomico', verbose_name='Estudio Socioeconómico'),
        ),
    ]
