# Generated by Django 3.2.3 on 2021-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='descripcion_ubicacion',
            field=models.TextField(blank=True, verbose_name='Referencias de ubicación'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_interior',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número interior'),
        ),
    ]
