# Generated by Django 3.2.3 on 2021-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0004_alter_beneficiario_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='dependientes_economicos',
            field=models.PositiveIntegerField(verbose_name='Número de dependeientes económicos'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='entre_vialidades',
            field=models.CharField(blank=True, max_length=50, verbose_name='Entre vialidades'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='integrantes_familia',
            field=models.PositiveIntegerField(verbose_name='Número de integrantes de la familia'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_exterior',
            field=models.PositiveIntegerField(verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_habitantes_vivienda',
            field=models.PositiveIntegerField(verbose_name='Número de habitantes en la vivienda'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_interior',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número interior'),
        ),
    ]
